### ISSUE TITLE
Integrity check fails on first boot when Orchid is installed.

### ISSUE THREAD

**Issue by Maxwelldoug** [Vanilla-OS/vib-fsguard#9]
### Issue Description

Testing has been done on VirtualBox with Linux and Windows hosts, KVM on a linux host, and hyper-v on a Windows host.

VirtualBox on Linux failed to install for unrelated reasons with incredibly unstable graphics drivers and the inability of the installer to read the drive.

All the other hypervisors, Vanilla installed "correctly" but failed integrity check. Upon further investigation, the FsGuard executable is replaced with what appears to be log data, which would explain the IC failure.

### Steps to Reproduce
-- disregard first two steps, this appears to not be exclusive to VMs
~~- Load a hypervisor (IE: Virtualbox, Hyper-V)
- Create a new VM (I used an 80GB drive, 8GB of ram, and 4 CPU cores, all other settings were tested first as default but changing them had no visible effect.)~~

- Install VanillaOS with the fairly obvious procedure
- Reboot when prompted and load current state (A)
- Observe IC fail. Bypassing IC boots correctly and seems to work, but attempting a forced update to fix the FsGuard executable unequivocally breaks both partitions, preventing Xorg or Wayland from launching in a current or previous state.

### On what version of Vanilla OS this happens?

Orchid, latest as of 2024/07/02

### Additional Information

The aforementioned issue with VirtualBox on Linux may be related to an issue discussed on the discord relating to the i915 drivers as the i915 chipset is used by default by VirtualBox on Linux hosts.

**Comment by Maxwelldoug** [comment]
Changed title as another user has confirmed my findings on physical hardware

**Comment by SanderBex** [comment]
I've gotten this on physical hardware installing on a laptop with an Nvidia 40 series GPU.
It's a fresh install I did today. Every boot, the IC fails. But when I continue booting, everything seems to work fine.

running `abroot status`:
```
ABRoot Partitions:
 • Present: vos-a ✓
 • Future: vos-b

Loaded Configuration: /etc/abroot/abroot.json

Device Specifications:
 • CPU: 12th Gen Intel(R) Core(TM) i5-12450H
 • GPU: [Intel Corporation Alder Lake-P GT1 [UHD Graphics] (rev 0c) NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] (rev a1)]
 • Memory: 15701 MB

ABImage:
 • Digest: 2491939eb6f0f1fcc3ce3baa0653c580c221d2f7146593319fa9f00a3f259d91
 • Timestamp: 2024-07-03 22:11:02
 • Image: ghcr.io/vanilla-os/nvidia:main

Kernel Arguments: %s quiet splash bgrt_disable $vt_handoff lsm=integrity nvidia-drm.modeset=1


Packages:
 • Added: 
 • Removed: 
 • Unstaged: 

Package agreement: false
```

If there is any other relevant info I can provide, lemme know :)

I'm gonna try to re-install first. I have doubts if that will fix anything, but I will update with the results
